//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public agent()
        {
            this.productsales = new HashSet<productsale>();
        }
    
        public int Id { get; set; }
        public Nullable<int> idTypeAgent { get; set; }
        public string NameAgent { get; set; }
        public string Mail { get; set; }
        public string Phone { get; set; }
        public string LogoAgent { get; set; }
        public string LegalAddress { get; set; }
        public Nullable<double> Prioritet { get; set; }
        public string Director { get; set; }
        public Nullable<long> INN { get; set; }
        public Nullable<long> KPP { get; set; }
    
        public virtual type_agents type_agents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productsale> productsales { get; set; }
    }
}
