//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesCompany
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalesCompanyEntities : DbContext
    {
        public SalesCompanyEntities()
            : base("name=SalesCompanyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agent> agents { get; set; }
        public virtual DbSet<HistotyAgent> HistotyAgents { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<productsale> productsales { get; set; }
        public virtual DbSet<type_agents> type_agents { get; set; }
        public virtual DbSet<type_product> type_product { get; set; }
        public virtual DbSet<VW_AgentDetails> VW_AgentDetails { get; set; }
    }
}
