//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistotyAgent
    {
        public int id { get; set; }
        public string NameAgent { get; set; }
        public string PrioritetOld { get; set; }
        public string PrioritetNew { get; set; }
    }
}
