//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.productsales = new HashSet<productsale>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string TypeProduct { get; set; }
        public Nullable<int> idTypeProduct { get; set; }
        public Nullable<long> VendorCode { get; set; }
        public Nullable<double> NumberOfPeopleForProduction { get; set; }
        public Nullable<decimal> MinimumPriceforanAgent { get; set; }
    
        public virtual type_product type_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productsale> productsales { get; set; }
    }
}
