//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_AgentDetails
    {
        public string Logo { get
            {
                if (LogoAgent == null)
                    return null;
                return "/Resources" + LogoAgent;
            } 
        }
        public string Name { get; set; }
        public string NameAgent { get; set; }
        public string Phone { get; set; }
        public Nullable<double> Prioritet { get; set; }
        public Nullable<int> AgentSale { get; set; }
        public Nullable<double> SalesCount { get; set; }
        public int Id { get; set; }
        public string LogoAgent { get; set; }
    }
}
